version: "3.9"

services:
  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile-dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public

  back:
    build:
      context: ./backend
      dockerfile: Dockerfile-dev
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
