version: "3.9"

services:
  front_prod:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - back_prod

  back_prod:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
